import { reactive, ref } from 'vue'
import { Coin, Clock, DataBoard, HelpFilled, InfoFilled, Key, MagicStick, Memo, Monitor, Money, Setting, SwitchButton, TrendCharts } from '@element-plus/icons-vue'
import { tabs } from '../constants/app'
import { localDateKey } from '../utils/format'

const appThemeStorageKey = 'omniproxy.appTheme'
const firstUseGuideStorageKey = 'omniproxy.firstRunGuideModalDismissed'

function shouldShowFirstUseGuide() {
  if (typeof window === 'undefined') return true
  return window.localStorage?.getItem(firstUseGuideStorageKey) !== '1'
}

export function createAppState() {
  const emptyBillingSummary = () => ({
    requestCount: 0,
    inputTokens: 0,
    outputTokens: 0,
    totalTokens: 0,
    dailyRows: [],
  })

  const state = {
    activeTab: ref('dashboard'),
    activeProvider: ref('openai'),
    mobileSidebarOpen: ref(false),
    tabIcons: {
      dashboard: DataBoard,
      'usage-trends': TrendCharts,
      billing: Money,
      quotas: Coin,
      tokens: Key,
      'openrouter-chat': Monitor,
      history: Clock,
      logs: Memo,
      quickstart: MagicStick,
      'gateway-routes': SwitchButton,
      settings: Setting,
      about: InfoFilled,
      help: HelpFilled,
    },
    navSections: [
      { label: '总览', items: tabs.filter((tab) => ['dashboard', 'usage-trends', 'billing', 'quotas'].includes(tab.key)) },
      { label: '运行', items: tabs.filter((tab) => ['tokens', 'history', 'logs', 'quickstart'].includes(tab.key)) },
      { label: '体验', items: tabs.filter((tab) => ['openrouter-chat'].includes(tab.key)) },
      { label: '系统', items: tabs.filter((tab) => ['gateway-routes', 'settings', 'about', 'help'].includes(tab.key)) },
    ],
    tabKeys: new Set(tabs.map((tab) => tab.key)),
    isDark: ref(false),
    windowMaximised: ref(false),
    loading: ref(false),
    codexConfiguring: ref(false),
    codexRestoring: ref(false),
    claudeModelsConfiguring: ref(false),
    claudeDesktopConfiguring: ref(false),
    claudeDesktopRestoring: ref(false),
    deepSeekTUIConfiguring: ref(false),
    geminiConfiguring: ref(false),
    opencodeConfiguring: ref(false),
    piConfiguring: ref(false),
    claudeCliRestoring: ref(false),
    deepSeekTUIRestoring: ref(false),
    geminiRestoring: ref(false),
    opencodeRestoring: ref(false),
    piRestoring: ref(false),
    refreshingProvider: ref(false),
    dataDirChanging: ref(false),
    autoStartChanging: ref(false),
    autoStartEnabled: ref(false),
    taskAutomationBrowserProfiles: ref([]),
    taskAutomationBrowserProfilesLoading: ref(false),
    taskAutomationBrowserProfilesError: ref(''),
    exportingHistory: ref(''),
    exportingTokens: ref(false),
    exportingCodexAuth: ref(false),
    codexAuthImporting: ref(false),
    batchImporting: ref(false),
    clearingBillingUsage: ref(false),
    clearingRequestHistory: ref(false),
    updateDiagnosticsLoading: ref(false),
    errorMessage: ref(''),
    successMessage: ref(''),
    quotaRefreshProgress: reactive({
      visible: false,
      percent: 0,
      total: 0,
      completed: 0,
      failed: 0,
      providerLabel: '',
      currentName: '',
    }),
    deleteCandidate: ref(null),
    deleteBusy: ref(false),
    toastAutoCloseMs: 4000,
    appThemeStorageKey,
    firstUseGuideStorageKey,
    timers: {
      toastTimer: null,
      realtimeTimer: null,
      historyRefreshSeq: 0,
      taskAutomationBrowserProfileSeq: 0,
    },
    validatingIds: reactive({}),
    refreshingTokenIds: reactive({}),
    togglingTokenIds: reactive({}),
    switchingOnlyTokenIds: reactive({}),
    tokens: ref([]),
    logs: ref([]),
    requestHistory: ref([]),
    requestHistorySummary: ref(null),
    emptyBillingSummary,
    billingSummary: ref(emptyBillingSummary()),
    requestHistoryFilters: ref({}),
    billingUsage: ref([]),
    billingDates: ref([]),
    selectedBillingDate: ref(localDateKey()),
    activeRequests: ref([]),
    openRouterModels: ref([]),
    openRouterModelsFetchedAt: ref(''),
    openRouterModelsCached: ref(false),
    openRouterModelsLoading: ref(false),
    openRouterModelsError: ref(''),
    updateDiagnostics: ref(null),
    selectedOpenRouterChatModel: ref(''),
    selectedHistoryEntry: ref(null),
    firstUseGuideVisible: ref(shouldShowFirstUseGuide()),
    firstUseGuideStepIndex: ref(0),
    subscriptionQuotaPage: ref(0),
    apiQuotaPage: ref(0),
    proxyStatus: reactive({ running: false, port: 3000 }),
    config: reactive({
      proxyPort: 3000,
      controlPort: 3890,
      schedulingMode: 'queue',
      websocketMode: 'enabled',
      checkBetaUpdates: false,
      taskAutomationEnabled: false,
      taskAutomationClients: ['codex', 'claude', 'claude-desktop'],
      taskAutomationLaunchMode: 'media',
      taskAutomationLaunchTarget: '',
      taskAutomationFallbackUrl: 'https://www.douyin.com',
      taskAutomationBrowser: 'default',
      taskAutomationBrowserUserDataDir: '',
      taskAutomationBrowserProfile: '',
      taskAutomationReturnToClient: true,
      taskAutomationIdleSeconds: 5,
      taskAutomationReturnDelaySeconds: 3,
      outboundProxyEnabled: false,
      outboundProxyUrl: 'http://127.0.0.1:10808',
      outboundProxyProviders: ['openai', 'anthropic', 'gemini', 'openrouter', 'zo', 'prem'],
      outboundProxyModels: ['gpt-*', 'claude-*', 'gemini-*', '*/*'],
      upstreamBaseUrl: 'https://api.openai.com',
      openaiBaseUrl: 'https://api.openai.com',
      anthropicBaseUrl: 'https://api.anthropic.com',
      deepseekBaseUrl: 'https://api.deepseek.com',
      deepseekAnthropicBaseUrl: 'https://api.deepseek.com/anthropic',
      kimiBaseUrl: 'https://api.kimi.com/coding',
      zhipuBaseUrl: 'https://open.bigmodel.cn/api/paas/v4',
      zhipuAnthropicBaseUrl: 'https://open.bigmodel.cn/api/anthropic',
      minimaxBaseUrl: 'https://api.minimaxi.com/v1',
      minimaxAnthropicBaseUrl: 'https://api.minimaxi.com/anthropic',
      geminiBaseUrl: 'https://generativelanguage.googleapis.com',
      openrouterBaseUrl: 'https://openrouter.ai/api/v1',
      tokenrouterBaseUrl: 'https://api.tokenrouter.io',
      sub2apiBaseUrl: 'https://aiapi.aicnio.com',
      newapiBaseUrl: 'http://127.0.0.1:3000',
      anyrouterBaseUrl: 'https://anyrouter.top',
      zoBaseUrl: 'https://api.zo.computer',
      premBaseUrl: 'http://127.0.0.1:3100',
      premAutoStartPcciProxy: true,
      customGatewayBaseUrl: '',
      customGatewayAnthropicBaseUrl: '',
      xiaomiBaseUrl: '',
      xiaomiApiBaseUrl: 'https://api.xiaomimimo.com/v1',
      xiaomiApiAnthropicBaseUrl: 'https://api.xiaomimimo.com/anthropic',
      xiaomiTokenPlanBaseUrl: 'https://token-plan-cn.xiaomimimo.com/v1',
      xiaomiTokenPlanAnthropicBaseUrl: 'https://token-plan-cn.xiaomimimo.com/anthropic',
      xiaomiTokenPlanSgpBaseUrl: 'https://token-plan-sgp.xiaomimimo.com/v1',
      xiaomiTokenPlanSgpAnthropicBaseUrl: 'https://token-plan-sgp.xiaomimimo.com/anthropic',
      xiaomiTokenPlanAmsBaseUrl: 'https://token-plan-ams.xiaomimimo.com/v1',
      xiaomiTokenPlanAmsAnthropicBaseUrl: 'https://token-plan-ams.xiaomimimo.com/anthropic',
      xiaomiCredentialPriority: 'mimo_token_plan',
      codexBaseUrl: 'https://chatgpt.com/backend-api/codex',
      gatewayRoutes: {
        codex: { provider: 'openai', credentialType: 'codex_auth_json', model: 'gpt-5.4' },
        claude: { provider: 'anthropic', credentialType: 'api_key', model: 'claude-sonnet-4-5-20250929' },
        openai: { provider: 'openai', credentialType: 'api_key', model: 'gpt-5.4' },
        gemini: { provider: 'gemini', credentialType: 'api_key', model: 'gemini-3-pro-preview' },
      },
      modelRoutes: {},
      codexUsageEndpoint: 'https://chatgpt.com/backend-api/wham/usage',
      switchThreshold: 15,
      maxRetries: 2,
      historyRetentionDays: 14,
    }),
    selectedCodexModel: ref('gpt-5.4'),
    dataDirectory: reactive({
      dataDir: '',
      bootstrapPath: '',
      envOverride: false,
      source: '',
      pendingDataDir: '',
      restartRequired: false,
    }),
    selectedClaudeModels: ref([]),
    appInfo: reactive({
      name: 'OmniProxy',
      version: 'dev',
      isDevelopment: true,
      updateEndpoint: '',
      platform: '',
      goVersion: '',
      executablePath: '',
      startedAt: '',
    }),
    form: reactive({
      visible: false,
      editingId: '',
      name: '',
      provider: 'openai',
      originalProvider: 'openai',
      credentialType: 'api_key',
      originalCredentialType: 'api_key',
      region: 'cn',
      baseUrl: '',
      tokenValue: '',
    }),
    batchImportForm: reactive({
      visible: false,
      provider: 'openai',
      baseUrl: '',
      tokenText: '',
    }),
    firstUseGuideSteps: [
      {
        step: '01',
        title: '添加上游账号',
        description: '先在账号管理里添加至少一个可用凭据。Codex auth.json、Claude OAuth JSON、API Key、Zo Access Token 都从这里进入。',
        actionLabel: '打开账号管理',
        actionKey: 'tokens',
        icon: Key,
      },
      {
        step: '02',
        title: '启动本地代理',
        description: '代理启动后，客户端只需要连接本机 loopback 地址；真实凭据由 OmniProxy 在请求转发时注入。',
        actionLabel: '启动代理',
        actionKey: 'proxy',
        icon: SwitchButton,
      },
      {
        step: '03',
        title: '写入客户端配置',
        description: '用一键配置把 Codex、Claude Code、Claude Desktop、OpenCode、Pi、Gemini 等客户端指向 OmniProxy。',
        actionLabel: '打开一键配置',
        actionKey: 'quickstart',
        icon: MagicStick,
      },
    ],
  }

  return state
}
