// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {history} from '../models';
import {config} from '../models';
import {token} from '../models';

export function ActiveProxyRequests():Promise<Array<main.activeRequestResponse>>;

export function AppInfo():Promise<main.appInfo>;

export function AutoStartStatus():Promise<Record<string, any>>;

export function BillingDates(arg1:number):Promise<Array<string>>;

export function BillingUsage(arg1:string):Promise<Array<history.DailyUsage>>;

export function CheckForUpdates():Promise<main.updateInfo>;

export function ChooseDataDirectory(arg1:boolean):Promise<config.DataDirectoryChangeResult>;

export function ClearBillingUsage():Promise<void>;

export function ClearRequestHistory():Promise<void>;

export function Config():Promise<config.Config>;

export function ConfigureCodex():Promise<main.codexConfigureResult>;

export function ConfigureDeepSeekClaude():Promise<main.mimoConfigureResult>;

export function ConfigureGemini():Promise<main.clientConfigureResult>;

export function ConfigureKimiClaude():Promise<main.mimoConfigureResult>;

export function ConfigureMimoClaude():Promise<main.mimoConfigureResult>;

export function ConfigureOpenCode():Promise<main.clientConfigureResult>;

export function ConfigureZhipuClaude():Promise<main.mimoConfigureResult>;

export function ControlAPI():Promise<string>;

export function CreateToken(arg1:token.UpsertRequest):Promise<main.tokenResponse>;

export function DataDirectory():Promise<config.DataDirectoryInfo>;

export function DeleteToken(arg1:string):Promise<void>;

export function DownloadUpdate(arg1:main.updateDownloadRequest):Promise<main.updateDownloadStatus>;

export function ExportCodexAuthFiles():Promise<main.codexAuthExportResult>;

export function ExportRequestHistory(arg1:string,arg2:history.Filter):Promise<string>;

export function ExportTokens():Promise<main.tokenExportResult>;

export function ImportMimoCookieFromHAR():Promise<main.mimoCookieImportResult>;

export function InstallDownloadedUpdate():Promise<main.updateDownloadStatus>;

export function Logs():Promise<Array<main.logResponse>>;

export function ProxyStatus():Promise<Record<string, any>>;

export function RequestHistory(arg1:history.Filter):Promise<Array<main.historyResponse>>;

export function RestoreCodex():Promise<main.codexConfigureResult>;

export function RestoreDeepSeekClaude():Promise<main.mimoConfigureResult>;

export function RestoreGemini():Promise<main.clientConfigureResult>;

export function RestoreKimiClaude():Promise<main.mimoConfigureResult>;

export function RestoreMimoClaude():Promise<main.mimoConfigureResult>;

export function RestoreOpenCode():Promise<main.clientConfigureResult>;

export function RestoreZhipuClaude():Promise<main.mimoConfigureResult>;

export function SaveConfig(arg1:config.Config):Promise<config.Config>;

export function SetAutoStart(arg1:boolean):Promise<Record<string, any>>;

export function SetTokenDisabled(arg1:string,arg2:boolean):Promise<main.tokenResponse>;

export function StartProxy():Promise<Record<string, any>>;

export function StopProxy():Promise<Record<string, any>>;

export function Tokens():Promise<Array<main.tokenResponse>>;

export function UpdateDownloadStatus():Promise<main.updateDownloadStatus>;

export function UpdateToken(arg1:string,arg2:token.UpsertRequest):Promise<main.tokenResponse>;

export function ValidateToken(arg1:string):Promise<main.validationResponse>;
