// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseDataDirectory(arg1) {
  return window['go']['main']['DesktopApp']['ChooseDataDirectory'](arg1);
}

export function ControlAPI() {
  return window['go']['main']['DesktopApp']['ControlAPI']();
}

export function DataDirectory() {
  return window['go']['main']['DesktopApp']['DataDirectory']();
}
