// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {config} from '../models';
import {token} from '../models';
import {history} from '../models';
import {logs} from '../models';
import {proxy} from '../models';

export function AutoStartStatus():Promise<Record<string, any>>;

export function CheckForUpdates():Promise<main.updateInfo>;

export function ChooseDataDirectory(arg1:boolean):Promise<config.DataDirectoryChangeResult>;

export function Config():Promise<config.Config>;

export function ConfigureCodex():Promise<main.codexConfigureResult>;

export function ConfigureDeepSeekClaude():Promise<main.mimoConfigureResult>;

export function ConfigureKimiClaude():Promise<main.mimoConfigureResult>;

export function ConfigureMimoClaude():Promise<main.mimoConfigureResult>;

export function ControlAPI():Promise<string>;

export function CreateToken(arg1:token.UpsertRequest):Promise<main.tokenResponse>;

export function DataDirectory():Promise<config.DataDirectoryInfo>;

export function DeleteToken(arg1:string):Promise<void>;

export function ExportRequestHistory(arg1:string,arg2:history.Filter):Promise<string>;

export function Logs():Promise<Array<logs.Entry>>;

export function ProxyStatus():Promise<Record<string, any>>;

export function RequestHistory(arg1:history.Filter):Promise<Array<history.Entry>>;

export function RestoreCodex():Promise<main.codexConfigureResult>;

export function RestoreDeepSeekClaude():Promise<main.mimoConfigureResult>;

export function RestoreKimiClaude():Promise<main.mimoConfigureResult>;

export function RestoreMimoClaude():Promise<main.mimoConfigureResult>;

export function SaveConfig(arg1:config.Config):Promise<config.Config>;

export function SetAutoStart(arg1:boolean):Promise<Record<string, any>>;

export function StartProxy():Promise<Record<string, any>>;

export function StopProxy():Promise<Record<string, any>>;

export function Tokens():Promise<Array<main.tokenResponse>>;

export function UpdateToken(arg1:string,arg2:token.UpsertRequest):Promise<main.tokenResponse>;

export function ValidateToken(arg1:string):Promise<proxy.ValidationResult>;
