// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {history} from '../models';
import {config} from '../models';
import {token} from '../models';
import {taskautomation} from '../models';

export function ActiveProxyRequests():Promise<Array<main.activeRequestResponse>>;

export function AppInfo():Promise<main.appInfo>;

export function AutoStartStatus():Promise<Record<string, any>>;

export function BillingDates(arg1:number):Promise<Array<string>>;

export function BillingSummary(arg1:number):Promise<history.BillingSummary>;

export function BillingUsage(arg1:string):Promise<Array<history.DailyUsage>>;

export function CancelUseOnlyToken(arg1:string):Promise<Array<main.tokenResponse>>;

export function CheckForUpdates():Promise<main.updateInfo>;

export function ChooseDataDirectory(arg1:boolean):Promise<config.DataDirectoryChangeResult>;

export function ClearBillingUsage():Promise<void>;

export function ClearRequestHistory():Promise<void>;

export function Config():Promise<config.Config>;

export function ConfigureClaudeDesktopModels(arg1:main.claudeModelsConfigureRequest):Promise<main.mimoConfigureResult>;

export function ConfigureClaudeModels(arg1:main.claudeModelsConfigureRequest):Promise<main.mimoConfigureResult>;

export function ConfigureCodex():Promise<main.codexConfigureResult>;

export function ConfigureDeepSeekTUI():Promise<main.clientConfigureResult>;

export function ConfigureGemini():Promise<main.clientConfigureResult>;

export function ConfigureOpenCode():Promise<main.clientConfigureResult>;

export function ConfigurePi():Promise<main.clientConfigureResult>;

export function ControlAPI():Promise<string>;

export function CreateToken(arg1:token.UpsertRequest):Promise<main.tokenResponse>;

export function DataDirectory():Promise<config.DataDirectoryInfo>;

export function DeleteToken(arg1:string):Promise<void>;

export function DownloadUpdate(arg1:main.updateDownloadRequest):Promise<main.updateDownloadStatus>;

export function ExportCodexAuthFiles():Promise<main.codexAuthExportResult>;

export function ExportRequestHistory(arg1:string,arg2:history.Filter):Promise<string>;

export function ExportTokens():Promise<main.tokenExportResult>;

export function ImportAPIKeys(arg1:main.apiKeyBatchImportRequest):Promise<main.apiKeyBatchImportResult>;

export function InstallDownloadedUpdate():Promise<main.updateDownloadStatus>;

export function Logs():Promise<Array<main.logResponse>>;

export function OpenRouterChat(arg1:main.openRouterChatRequest):Promise<main.openRouterChatResponse>;

export function OpenRouterModels(arg1:boolean):Promise<main.openRouterModelsResponse>;

export function ProxyStatus():Promise<Record<string, any>>;

export function RefreshTokenAuth(arg1:string):Promise<main.tokenResponse>;

export function RequestHistory(arg1:history.Filter):Promise<Array<main.historyResponse>>;

export function RequestHistorySummary(arg1:history.Filter,arg2:number):Promise<history.Summary>;

export function RestoreClaude():Promise<main.mimoConfigureResult>;

export function RestoreClaudeDesktop():Promise<main.mimoConfigureResult>;

export function RestoreCodex():Promise<main.codexConfigureResult>;

export function RestoreDeepSeekTUI():Promise<main.clientConfigureResult>;

export function RestoreGemini():Promise<main.clientConfigureResult>;

export function RestoreOpenCode():Promise<main.clientConfigureResult>;

export function RestorePi():Promise<main.clientConfigureResult>;

export function SaveConfig(arg1:config.Config):Promise<config.Config>;

export function SetAutoStart(arg1:boolean):Promise<Record<string, any>>;

export function SetTokenDisabled(arg1:string,arg2:boolean):Promise<main.tokenResponse>;

export function SetTokenSelected(arg1:string,arg2:boolean):Promise<Array<main.tokenResponse>>;

export function StartProxy():Promise<Record<string, any>>;

export function StopProxy():Promise<Record<string, any>>;

export function TaskAutomationBrowserProfiles(arg1:string):Promise<Array<taskautomation.BrowserProfile>>;

export function Tokens():Promise<Array<main.tokenResponse>>;

export function UpdateDownloadStatus():Promise<main.updateDownloadStatus>;

export function UpdateToken(arg1:string,arg2:token.UpsertRequest):Promise<main.tokenResponse>;

export function UseOnlyToken(arg1:string):Promise<Array<main.tokenResponse>>;

export function ValidateToken(arg1:string):Promise<main.validationResponse>;
