export const knownClientTools = [
  { key: 'codex', label: 'Codex' },
  { key: 'claude', label: 'Claude Code' },
  { key: 'claude-desktop', label: 'Claude Code Desktop' },
  { key: 'gemini', label: 'Gemini CLI' },
  { key: 'opencode', label: 'OpenCode' },
  { key: 'pi', label: 'Pi Coding Agent' },
  { key: 'deepseek-tui', label: 'DeepSeek-TUI' },
  { key: 'openrouter', label: 'OpenRouter' },
  { key: 'tokenrouter', label: 'TokenRouter' },
  { key: 'sub2api', label: 'sub2api' },
  { key: 'newapi', label: 'new-api' },
  { key: 'cursor', label: 'Cursor' },
  { key: 'vscode', label: 'VS Code' },
  { key: 'windsurf', label: 'Windsurf' },
  { key: 'aider', label: 'Aider' },
  { key: 'continue', label: 'Continue' },
  { key: 'custom', label: '自定义网关' },
  { key: 'api', label: 'API Client' },
]
