export function buildThirdPartyEndpointGroups(port) {
  const safePort = Number(port) || 3000
  const base = `http://127.0.0.1:${safePort}`

  return [
    {
      title: 'OpenAI 兼容客户端',
      note: 'Cherry Studio、Open WebUI、Continue、Chatbox 等支持 OpenAI-compatible 的客户端优先看这里。',
      endpoints: [
        {
          name: 'OmniProxy OpenAI',
          protocol: 'OpenAI Chat / Responses',
          baseUrl: `${base}/v1`,
          apiKey: 'omniproxy-local',
          models: '使用 OpenAI 账号池里的模型名，例如 gpt-5.4',
          use: '通用 OpenAI 兼容入口，适合自定义客户端直接接入。',
        },
        {
          name: 'Codex Chat',
          protocol: 'OpenAI Chat',
          baseUrl: `${base}/codex/v1`,
          apiKey: 'omniproxy-local',
          models: 'gpt-5.5 / gpt-5.4',
          use: '用 Codex auth.json 账号承接 Chat Completions 请求。',
        },
        {
          name: 'Zo Computer',
          protocol: 'OpenAI Chat / Responses',
          baseUrl: `${base}/zo/v1`,
          apiKey: 'omniproxy-local',
          models: 'gpt-5.5 / gpt-5.4 / claude-opus-4-7 / gemini-3.1-pro / glm-5',
          use: '适合把 Zo Token 暴露给 Cherry Studio 这类 OpenAI-compatible 客户端。',
        },
        {
          name: 'OpenRouter',
          protocol: 'OpenAI Chat',
          baseUrl: `${base}/openrouter/v1`,
          apiKey: 'omniproxy-local',
          models: 'openrouter/auto 或 OpenRouter 模型 ID',
          use: '使用 OpenRouter API Key 账号池。',
        },
        {
          name: 'TokenRouter',
          protocol: 'OpenAI Chat',
          baseUrl: `${base}/tokenrouter/v1`,
          apiKey: 'omniproxy-local',
          models: 'auto:balance / auto:quality / auto:speed / auto:cost',
          use: '使用 TokenRouter API Key 账号池和自动路由模型。',
        },
        {
          name: 'sub2api',
          protocol: 'OpenAI Chat / Responses',
          baseUrl: `${base}/sub2api/v1`,
          apiKey: 'omniproxy-local',
          models: '由 sub2api 上游决定',
          use: '转发到 sub2api OpenAI 兼容网关。',
        },
        {
          name: 'new-api',
          protocol: 'OpenAI Chat / Responses',
          baseUrl: `${base}/newapi/v1`,
          apiKey: 'omniproxy-local',
          models: '由 new-api 上游决定',
          use: '转发到 new-api OpenAI 兼容网关。',
        },
        {
          name: 'AnyRouter',
          protocol: 'OpenAI Responses',
          baseUrl: `${base}/anyrouter/v1`,
          apiKey: 'omniproxy-local',
          models: 'gpt-5-codex / gpt-5.5',
          use: '转发到 AnyRouter 的 OpenAI/Codex 兼容入口。',
        },
        {
          name: '自定义网关',
          protocol: 'OpenAI Chat',
          baseUrl: `${base}/custom/v1`,
          apiKey: 'omniproxy-local',
          models: 'custom-model 或上游支持的模型名',
          use: '转发到设置页填写的自定义 OpenAI 兼容网关。',
        },
      ],
    },
    {
      title: 'Anthropic / Claude 兼容客户端',
      note: '适合支持 Anthropic Messages API 的客户端。Claude Desktop 建议用一键配置写入 3P Gateway Profile。',
      endpoints: [
        {
          name: 'Claude Router',
          protocol: 'Anthropic Messages',
          baseUrl: `${base}/anthropic-router`,
          apiKey: 'omniproxy',
          models: 'deepseek-v4-pro[1m] / kimi-for-coding / glm-5.1 / claude-opus-4-7',
          use: '按模型分流到 DeepSeek、MiMo、Kimi、GLM、Zo 或 Anthropic。',
        },
        {
          name: 'Anthropic 官方账号池',
          protocol: 'Anthropic Messages',
          baseUrl: `${base}/anthropic/v1`,
          apiKey: 'omniproxy-local',
          models: 'Claude 模型名',
          use: '使用 Anthropic API Key 或 Claude OAuth JSON 账号池。',
        },
        {
          name: 'Zo Anthropic',
          protocol: 'Anthropic Messages',
          baseUrl: `${base}/zo/v1`,
          apiKey: 'omniproxy-local',
          models: 'claude-opus-4-7 / claude-sonnet-4-6',
          use: '用 Zo Token 适配 Anthropic Messages 请求。',
        },
        {
          name: 'sub2api Anthropic',
          protocol: 'Anthropic Messages',
          baseUrl: `${base}/sub2api/anthropic/v1`,
          apiKey: 'omniproxy-local',
          models: '由 sub2api 上游决定',
          use: '转发到 sub2api Anthropic 兼容入口。',
        },
        {
          name: 'new-api Anthropic',
          protocol: 'Anthropic Messages',
          baseUrl: `${base}/newapi/anthropic/v1`,
          apiKey: 'omniproxy-local',
          models: '由 new-api 上游决定',
          use: '转发到 new-api Anthropic 兼容入口。',
        },
        {
          name: 'AnyRouter Anthropic',
          protocol: 'Anthropic Messages',
          baseUrl: `${base}/anyrouter/anthropic/v1`,
          apiKey: 'omniproxy-local',
          models: 'claude-opus-4-5-20251101',
          use: '转发到 AnyRouter 的 Claude Code/Anthropic 兼容入口。',
        },
        {
          name: '自定义 Anthropic 网关',
          protocol: 'Anthropic Messages',
          baseUrl: `${base}/custom/anthropic/v1`,
          apiKey: 'omniproxy-local',
          models: 'custom-model 或上游支持的模型名',
          use: '转发到设置页填写的自定义 Anthropic 兼容网关。',
        },
      ],
    },
    {
      title: '厂商直连与原生协议',
      note: '当客户端明确支持某个厂商协议，或你想固定走某个账号池时使用。',
      endpoints: [
        {
          name: 'DeepSeek',
          protocol: 'OpenAI Chat',
          baseUrl: `${base}/deepseek/v1`,
          apiKey: 'omniproxy-local',
          models: 'deepseek-v4-pro / deepseek-v4-flash',
          use: '固定使用 DeepSeek API Key 账号池。',
        },
        {
          name: 'Kimi',
          protocol: 'OpenAI Chat',
          baseUrl: `${base}/kimi/v1`,
          apiKey: 'omniproxy-local',
          models: 'kimi-for-coding',
          use: '固定使用 Kimi API Key 账号池。',
        },
        {
          name: 'Xiaomi MiMo',
          protocol: 'OpenAI Chat',
          baseUrl: `${base}/xiaomi/v1`,
          apiKey: 'omniproxy-local',
          models: 'mimo-v2.5-pro / mimo-v2.5',
          use: '固定使用 MiMo API Key 或 Token Plan 账号池。',
        },
        {
          name: 'Zhipu GLM',
          protocol: 'OpenAI Chat',
          baseUrl: `${base}/zhipu/v1`,
          apiKey: 'omniproxy-local',
          models: 'glm-5.1',
          use: '固定使用 Zhipu GLM 账号池。',
        },
        {
          name: 'MiniMax',
          protocol: 'OpenAI Chat',
          baseUrl: `${base}/minimax/v1`,
          apiKey: 'omniproxy-local',
          models: 'MiniMax-M2.7',
          use: '固定使用 MiniMax API Key 账号池。',
        },
        {
          name: 'Gemini Native',
          protocol: 'Gemini API',
          baseUrl: `${base}/gemini`,
          apiKey: 'omniproxy-local',
          models: 'gemini-3-pro-preview / gemini-3-flash-preview',
          use: '用于支持 Gemini 原生 API 的客户端。',
        },
        {
          name: 'sub2api Gemini',
          protocol: 'Gemini API',
          baseUrl: `${base}/sub2api/gemini`,
          apiKey: 'omniproxy-local',
          models: '由 sub2api 上游决定',
          use: '转发到 sub2api Gemini 兼容入口。',
        },
        {
          name: 'new-api Gemini',
          protocol: 'Gemini API',
          baseUrl: `${base}/newapi/gemini`,
          apiKey: 'omniproxy-local',
          models: '由 new-api 上游决定',
          use: '转发到 new-api Gemini 兼容入口。',
        },
      ],
    },
    {
      title: '编程工具路由',
      note: '这些入口也可手动配置，但通常优先使用“一键配置”。',
      endpoints: [
        {
          name: 'Codex backend',
          protocol: 'Codex backend',
          baseUrl: `${base}/backend-api/codex`,
          apiKey: 'omniproxy-local',
          models: 'gpt-5.5 / gpt-5.4',
          use: 'Codex CLI backend API，使用 OpenAI Codex auth.json 账号。',
        },
        {
          name: 'OpenCode Router',
          protocol: 'OpenAI Chat',
          baseUrl: `${base}/opencode-router/v1`,
          apiKey: 'omniproxy-local',
          models: 'gpt-5.4 / deepseek-v4-pro / glm-5.1 / mimo-v2.5-pro',
          use: 'OpenCode 按模型自动分流。',
        },
        {
          name: 'Pi Router',
          protocol: 'OpenAI Chat',
          baseUrl: `${base}/pi-router/v1`,
          apiKey: 'omniproxy-local',
          models: 'gpt-5.4 / auto:balance / openrouter/auto / custom-model',
          use: 'Pi Coding Agent 按 provider 和模型自动分流。',
        },
        {
          name: 'Claude Desktop Gateway',
          protocol: 'Claude Desktop 3P Gateway',
          baseUrl: `${base}/claude-desktop`,
          apiKey: 'omniproxy-claude-desktop',
          models: '由 Claude Desktop Profile 映射决定',
          use: '仅用于 Claude Desktop 3P Gateway；建议通过一键配置写入。',
        },
      ],
    },
  ]
}
