// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActiveProxyRequests() {
  return window['go']['main']['DesktopApp']['ActiveProxyRequests']();
}

export function AppInfo() {
  return window['go']['main']['DesktopApp']['AppInfo']();
}

export function AutoStartStatus() {
  return window['go']['main']['DesktopApp']['AutoStartStatus']();
}

export function BillingDates(arg1) {
  return window['go']['main']['DesktopApp']['BillingDates'](arg1);
}

export function BillingSummary(arg1) {
  return window['go']['main']['DesktopApp']['BillingSummary'](arg1);
}

export function BillingUsage(arg1) {
  return window['go']['main']['DesktopApp']['BillingUsage'](arg1);
}

export function CancelUseOnlyToken(arg1) {
  return window['go']['main']['DesktopApp']['CancelUseOnlyToken'](arg1);
}

export function CheckForUpdates() {
  return window['go']['main']['DesktopApp']['CheckForUpdates']();
}

export function ChooseDataDirectory(arg1) {
  return window['go']['main']['DesktopApp']['ChooseDataDirectory'](arg1);
}

export function ClearBillingUsage() {
  return window['go']['main']['DesktopApp']['ClearBillingUsage']();
}

export function ClearRequestHistory() {
  return window['go']['main']['DesktopApp']['ClearRequestHistory']();
}

export function Config() {
  return window['go']['main']['DesktopApp']['Config']();
}

export function ConfigureClaudeDesktopModels(arg1) {
  return window['go']['main']['DesktopApp']['ConfigureClaudeDesktopModels'](arg1);
}

export function ConfigureClaudeModels(arg1) {
  return window['go']['main']['DesktopApp']['ConfigureClaudeModels'](arg1);
}

export function ConfigureCodex() {
  return window['go']['main']['DesktopApp']['ConfigureCodex']();
}

export function ConfigureDeepSeekTUI() {
  return window['go']['main']['DesktopApp']['ConfigureDeepSeekTUI']();
}

export function ConfigureGemini() {
  return window['go']['main']['DesktopApp']['ConfigureGemini']();
}

export function ConfigureOpenCode() {
  return window['go']['main']['DesktopApp']['ConfigureOpenCode']();
}

export function ConfigurePi() {
  return window['go']['main']['DesktopApp']['ConfigurePi']();
}

export function ControlAPI() {
  return window['go']['main']['DesktopApp']['ControlAPI']();
}

export function CreateToken(arg1) {
  return window['go']['main']['DesktopApp']['CreateToken'](arg1);
}

export function DataDirectory() {
  return window['go']['main']['DesktopApp']['DataDirectory']();
}

export function DeleteToken(arg1) {
  return window['go']['main']['DesktopApp']['DeleteToken'](arg1);
}

export function DownloadUpdate(arg1) {
  return window['go']['main']['DesktopApp']['DownloadUpdate'](arg1);
}

export function ExportCodexAuthFiles() {
  return window['go']['main']['DesktopApp']['ExportCodexAuthFiles']();
}

export function ExportRequestHistory(arg1, arg2) {
  return window['go']['main']['DesktopApp']['ExportRequestHistory'](arg1, arg2);
}

export function ExportTokens() {
  return window['go']['main']['DesktopApp']['ExportTokens']();
}

export function ImportAPIKeys(arg1) {
  return window['go']['main']['DesktopApp']['ImportAPIKeys'](arg1);
}

export function InstallDownloadedUpdate() {
  return window['go']['main']['DesktopApp']['InstallDownloadedUpdate']();
}

export function Logs() {
  return window['go']['main']['DesktopApp']['Logs']();
}

export function OpenRouterChat(arg1) {
  return window['go']['main']['DesktopApp']['OpenRouterChat'](arg1);
}

export function OpenRouterModels(arg1) {
  return window['go']['main']['DesktopApp']['OpenRouterModels'](arg1);
}

export function ProxyStatus() {
  return window['go']['main']['DesktopApp']['ProxyStatus']();
}

export function RefreshTokenAuth(arg1) {
  return window['go']['main']['DesktopApp']['RefreshTokenAuth'](arg1);
}

export function RequestHistory(arg1) {
  return window['go']['main']['DesktopApp']['RequestHistory'](arg1);
}

export function RequestHistorySummary(arg1, arg2) {
  return window['go']['main']['DesktopApp']['RequestHistorySummary'](arg1, arg2);
}

export function RestoreClaude() {
  return window['go']['main']['DesktopApp']['RestoreClaude']();
}

export function RestoreClaudeDesktop() {
  return window['go']['main']['DesktopApp']['RestoreClaudeDesktop']();
}

export function RestoreCodex() {
  return window['go']['main']['DesktopApp']['RestoreCodex']();
}

export function RestoreDeepSeekTUI() {
  return window['go']['main']['DesktopApp']['RestoreDeepSeekTUI']();
}

export function RestoreGemini() {
  return window['go']['main']['DesktopApp']['RestoreGemini']();
}

export function RestoreOpenCode() {
  return window['go']['main']['DesktopApp']['RestoreOpenCode']();
}

export function RestorePi() {
  return window['go']['main']['DesktopApp']['RestorePi']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['DesktopApp']['SaveConfig'](arg1);
}

export function SetAutoStart(arg1) {
  return window['go']['main']['DesktopApp']['SetAutoStart'](arg1);
}

export function SetTokenDisabled(arg1, arg2) {
  return window['go']['main']['DesktopApp']['SetTokenDisabled'](arg1, arg2);
}

export function SetTokenSelected(arg1, arg2) {
  return window['go']['main']['DesktopApp']['SetTokenSelected'](arg1, arg2);
}

export function StartProxy() {
  return window['go']['main']['DesktopApp']['StartProxy']();
}

export function StopProxy() {
  return window['go']['main']['DesktopApp']['StopProxy']();
}

export function TaskAutomationBrowserProfiles(arg1) {
  return window['go']['main']['DesktopApp']['TaskAutomationBrowserProfiles'](arg1);
}

export function Tokens() {
  return window['go']['main']['DesktopApp']['Tokens']();
}

export function UpdateDownloadStatus() {
  return window['go']['main']['DesktopApp']['UpdateDownloadStatus']();
}

export function UpdateToken(arg1, arg2) {
  return window['go']['main']['DesktopApp']['UpdateToken'](arg1, arg2);
}

export function UseOnlyToken(arg1) {
  return window['go']['main']['DesktopApp']['UseOnlyToken'](arg1);
}

export function ValidateToken(arg1) {
  return window['go']['main']['DesktopApp']['ValidateToken'](arg1);
}
